language: node_js
node_js:
  - 11
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  api_key:
    secure: 88d08eca-dce9-4886-96e1-ba254e77604c
  app: react-tests
  on:
    repo: gjlacerda/react-tests
before_script:
  - yarn build
  - yarn start 
script:
  - yarn run cypress run --record --key 06463f25-18d9-4517-8d6e-9c9ecd29a90a
after_success:
  - yarn test:coverage